services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    repo: https://github.com/deranalabs/rest-api-project
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
